version: 2
jobs:
  build:
    working_directory: ~/marko-jest
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: yarn lint
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: yarn test --coverage && cat ./.coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - store_artifacts:
          path: .coverage/lcov-report
          destination: coverage
      - store_test_results:
          path: .coverage/clover.xml
